name: salesiq_mobilisten
description: Mobilisten enables you to give your users the best in-app live chat experience. Mobilisten provides drop-in in-app chat and knowledge base.
version: 2.0.0
repository: https://github.com/zoho/salesiq-mobilisten-flutter
homepage: https://mobilisten.io/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.zohosalesiq.plugin
        pluginClass: MobilistenPlugin
      ios:
        pluginClass: MobilistenPlugin
      web:
        pluginClass: MobilistenWebPlugin
        fileName: salesiq_mobilisten_web.dart

